"use strict";var g=Object.create;var P=Object.defineProperty;var D=Object.getOwnPropertyDescriptor;var I=Object.getOwnPropertyNames;var A=Object.getPrototypeOf,w=Object.prototype.hasOwnProperty;var G=(o,t)=>{for(var e in t)P(o,e,{get:t[e],enumerable:!0})},R=(o,t,e,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of I(t))!w.call(o,s)&&s!==e&&P(o,s,{get:()=>t[s],enumerable:!(n=D(t,s))||n.enumerable});return o};var L=(o,t,e)=>(e=o!=null?g(A(o)):{},R(t||!o||!o.__esModule?P(e,"default",{value:o,enumerable:!0}):e,o)),M=o=>R(P({},"__esModule",{value:!0}),o);var U={};G(U,{DPOPayment:()=>d});module.exports=M(U);var h=L(require("axios")),O=h.default.create({baseURL:process.env.DPO_BASE_URL||"https://secure.3gdirectpay.com/API",headers:{"Content-Type":"application/xml"}});var c=class extends Error{code;constructor(t,e=0){super(t),this.name="DPOError",this.code=e}};var k=require("axios");function y(o){return o.replace(/[\s_-]+(\w)/g,function(t,e){return e.toUpperCase()}).replace(/(?:^\w|[A-Z]|\b\w)/g,function(t,e){return e===0?t.toLowerCase():t.toUpperCase()}).replace(/\s+/g,"")}var b=require("fast-xml-parser"),C=o=>new b.XMLParser().parse(o);var p=(o,t=!0)=>{let e=C(o),n=e.API3G?.StatusCode||e.API3G?.Result,s=e.API3G?.ResultExplanation||"success",i=Object.entries(e.API3G).map(([m,a])=>{if(typeof a=="object"&&a!==null){let T=Object.entries(a).map(([u,l])=>({[y(u)]:l})).reduce((u,l)=>({...u,...l}));return{[y(m)]:T}}return{[y(m)]:a}}).reduce((m,a)=>({...m,...a}));switch(t&&(delete i.result,delete i.resultExplanation),n){case 0:case 130:case 900:case"success":return{...i,statusCode:200,message:s};default:return{...i,statusCode:400,message:s}}},f=o=>{try{return{dpoJsonResponse:p(o,!1),dpoXMLResponse:`
<?xml version="1.0" encoding="UTF-8"?>
<API3G>  
  <Response>OK</Response>
</API3G>
`}}catch(t){return{dpoJsonResponse:{status:"error",statusCode:500,message:t.message},dpoXMLResponse:`
<?xml version="1.0" encoding="UTF-8"?>
<API3G>
  <Response>Failed</Response>
  <Result>Failed</Result>
  <ResultExplanation>${t.message}</ResultExplanation>
</API3G>
`}}};var r=o=>{if((0,k.isAxiosError)(o)){delete o.response?.data["?xml"];let t=p(o.response?.data);throw new c(t,o.response?.status)}throw o};var j=require("fast-xml-parser"),x=o=>`<?xml version="1.0" encoding="utf-8"?>${new j.XMLBuilder().build(o)}`;var d=class{companyToken;apiVersion;paymentURL;constructor({companyToken:t,apiVersion:e="v6"}){this.companyToken=t,this.apiVersion=e,this.paymentURL=process.env.DPO_PAYMENT_URL||"https://secure.3gdirectpay.com/payv3.php"}async processPaymentResponse(t){let e=x(t),n=await O.post(`/${this.apiVersion}/`,e);delete n.data["?xml"];let s=p(n.data);if(s.statusCode!==200)throw new c(JSON.stringify(s),s.statusCode);return s}async initiatePayment(t){try{let e={API3G:{CompanyToken:this.companyToken,Request:"createToken",...t}},n=await this.processPaymentResponse(e);return{...n,paymentURL:`${this.paymentURL}?ID=${n.transToken}`}}catch(e){return r(e)}}chargeMobilePayment(t){try{let e={API3G:{CompanyToken:this.companyToken,Request:"chargeTokenMobile",...t}};return this.processPaymentResponse(e)}catch(e){return r(e)}}chargeCardPayment(t){try{let e={API3G:{CompanyToken:this.companyToken,Request:"chargeTokenCreditCard",...t}};return this.processPaymentResponse(e)}catch(e){return r(e)}}refundPayment(t){try{let e={API3G:{CompanyToken:this.companyToken,Request:"refundToken",...t}};return this.processPaymentResponse(e)}catch(e){return r(e)}}cancelPayment(t){try{let e={API3G:{CompanyToken:this.companyToken,Request:"cancelToken",...t}};return this.processPaymentResponse(e)}catch(e){return r(e)}}checkPaymentStatus(t){try{let e={API3G:{CompanyToken:this.companyToken,Request:"verifyToken",...t}};return this.processPaymentResponse(e)}catch(e){return r(e)}}parseWebhookXML(t){return f(t)}};0&&(module.exports={DPOPayment});
