name: Release
on:
  release:
    types: [prereleased, released]
  push: 
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write
  id-token: write

jobs:
  publish:
    timeout-minutes: 5
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          cache: yarn
          node-version: lts/*
      - run: yarn install
      - run: yarn audit:fix
      - run: yarn audit signatures
      - run: yarn build
      - run: git config --global user.name Patrick Kabwe
      - run: git config --global user.email patrickkabwe@github.com
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn clean
