name: Test

on:
  release:
    types: [prereleased, released]

  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always

jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 22

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5
      - run: git config --global user.name Patrick Kabwe
      - run: git config --global user.email patrickkabwe@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn audit:fix
      - run: yarn audit signatures
      - run: yarn test

  test:
    runs-on: ubuntu-latest
    needs:
      - test_matrix
    if: ${{ !cancelled() }}
    steps:
      - name: All matrix versions passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some matrix version failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
